### ISSUE TITLE
你好,我也正在学这个.

### ISSUE THREAD

**Issue by uinz** [Tuluobo/Stanford_IOS8_Swift_Open_Courses_Demo#1]
有机会交流一下
我没有oc基础
会点js

前段时间在搞react 和 react native

**Comment by uinz** [comment]
请问你在哪里看视频的,itunes里看载我会卡死
其他地方都是flash的 看得好烫..

**Comment by Tuluobo** [comment]
我在github下载的，地址https://github.com/X140Yu/Developing_iOS_8_Apps_With_Swift ，有中文字幕
